tap "derailed/k9s"
tap "siderolabs/tap"

brew "argocd"
brew "awscli"
brew "coreutils"
brew "derailed/k9s/k9s"
brew "direnv"
brew "docker"
brew "fzf"
brew "gh"
brew "git"
brew "golangci-lint"
brew "helm"
brew "jq"
brew "kubectl"
brew "kubectx"
brew "make"
brew "mas"
brew "readline"
brew "shellcheck"
brew "shfmt"
brew "siderolabs/tap/talosctl"
brew "tfenv"
brew "tree"
brew "vim"
brew "wget"
brew "yq"

cask "hiddenbar"
cask "karabiner-elements"
cask "logi-options+"
cask "monitorcontrol"
cask "raycast"
cask "terraform-linters/tap/tflint"
cask "visual-studio-code"

mas "Bitwarden", id: 1352778147
mas "WireGuard", id: 1451685025

